### PR TITLE
TypeScript Rewrite

### PR DESCRIPTION
**Pull request by Jejebecarte**
A simple rewrite of the bot in TS

### CODE REVIEW

**Comment by Jejebecarte** [comment]
Chat emojis, such as guild ranks, are currently not implemented. The current plan is to create a command to upload these emojis to the given server, however this may introduce problems with emoji slots in certain servers. I'll think it through for a while, and if you've got any ideas, they're all welcome.

**Comment by ElijahRus250** [comment]
you just love rewriting stuff

**Comment by Jejebecarte** [comment]
Well maybe if I didn't write such bad code in the first place I wouldn't have to 😃

**Comment by Jejebecarte** [comment]
After thinking about it, I won't be merging the PR until I properly sort out guild rank upgrade emojis. I'd like the bot to be as polished as possible - otherwise it's kind of a step backwards.

**Comment by Jejebecarte** [comment]
And I believe that's it... can't think of anything more to add really.

**Pull request merged**
